" no need to be Vi-compatbile
set nocompatible

" source ~/.vimrc.before if it exists.
if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif

" line numbers are good
set number

" enable hidden buffers
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" turn on syntax highlighting
if &t_Co > 2 || has("gui_running")
  syntax on
endif

" set leader key
let mapleader=","

" initialize Vundle
if filereadable(expand("~/.vim/vundles.vim"))
  source ~/.vim/vundles.vim
endif

" store swap files while working
silent execute '!mkdir -p ~/.vim/tmp/swap'
set swapfile
set directory=~/.vim/tmp/swap,/tmp

" make a backup before overwriting a file
silent execute '!mkdir -p ~/.vim/tmp/backup'
set backup writebackup
set backupdir=~/.vim/tmp/backup

" persistent undo via text files
silent execute '!mkdir -p ~/.vim/tmp/undo'
set undofile
set undodir=~/.vim/tmp/undo

" indentation settings
set smartindent
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

if  has("autocmd")
  filetype plugin indent on
else
  set autoindent
endif

" don't wrap lines
set nowrap
" wrap lines at convenient points
set linebreak

" fold settings
set nofoldenable        " don't fold by default
set foldmethod=indent   " fold based on indent
set foldnestmax=3       " deepest fold is 3 levels

" wildmode completion
set wildmode=list:longest
" stuff to ignore when tab completing
set wildignore=*.o,*.obj,*~
set wildignore+=*vim/tmp*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

" easy on the eyes side-scrolling
set sidescroll=1

" Enable mouse mode
set mouse=a

" Color scheme
colorscheme Tomorrow-Night

" Line length column
set colorcolumn=80

" mark search results
set hlsearch

" mark tabs, trailing whitespace
set list
set listchars=tab:▸\ ,eol:¬,trail:·

" source ~/.vimrc.after if it exists.
if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif
