filetype plugin indent on

" turn on line numbers
set number

" expand tabs
set expandtab
set tabstop=2 shiftwidth=2 smarttab

" mark tabs, trailing whitespace
set list
set listchars=tab:▸\ ,eol:¬,trail:·

" Show 80 characters column line
set colorcolumn=80

" set leader key
let g:mapleader=","

" allow escaping with jk
inoremap jk <esc>

" go to last edit location
nnoremap <Leader>. '.

" easy window splits
nnoremap <silent> vv <C-w>v
nnoremap <silent> ss <C-w>s

if has('nvim')
  " fix <C-h> (https://github.com/neovim/neovim/issues/2048)
  nmap <BS> <C-h>

  " exit terminal mode
  tnoremap <Leader>e <C-\><C-n>
end

" easy window navigation
nnoremap <silent> <C-h> <C-w>h
nnoremap <silent> <C-j> <C-w>j
nnoremap <silent> <C-k> <C-w>k
nnoremap <silent> <C-l> <C-w>l

" leave current buffer only
nnoremap <silent> <C-w>b :Bufonly<CR>

" system clipboard
vmap <Leader>y "*y
map <Leader>p "*p<CR>
map <Leader>P "*P<CR>

" easy file navigation http://vimcasts.org/e/14
cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<cr>
map <leader>ew :e %%
map <leader>es :sp %%
map <leader>ev :vsp %%
map <leader>et :tabe %%

" Sudo save http://stackoverflow.com/a/7078429/107085
cmap w!! w !sudo tee > /dev/null %

" diff vertically
set diffopt+=vertical

" turn on spellchecker in Git commit messages
autocmd FileType gitcommit setlocal spell

" load installed plugs
source ~/.nvim/plugs.vim

" color scheme
color Tomorrow-Night-Eighties

" run neomake on the current file on every write
autocmd! BufWritePost * Neomake

" directory configuration for Notes
let g:notes_directories = ['~/Documents/Notes']

" vim-test configuration
let test#strategy = 'neoterm'
let test#ruby#rspec#executable = 'spring rspec'
nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>T :TestFile<CR>
nmap <silent> <leader>a :TestSuite<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>
