# Executes commands at login pre-zshrc.
#
# Based on Prezto's zprofile:
# https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zprofile

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export VISUAL='nvim'
export EDITOR="${VISUAL}"
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Go path
export GOPATH="$HOME/dev/go"

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin
  /usr/local/{bin,sbin}
  $HOME/Library/Python/2.7/bin
  $GOPATH/bin
  $path
)

if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then
  source $HOME/.nix-profile/etc/profile.d/nix.sh;
fi

if [[ -d "$HOME/.homebrew" ]]; then
  path=($HOME/.homebrew/bin $path)
  export PYTHONPATH=$HOME/.homebrew/lib/python2.7/site-packages:$PYTHONPATH
fi

if [[ -d "$HOME/.npm-packages" ]]; then
  path=($HOME/.npm-packages/bin $path)
fi

# Tomcat path
if [[ -s "$HOME/.homebrew/Cellar/tomcat6/6.0.39" ]]; then
  path=($HOME/.homebrew/Cellar/tomcat6/6.0.39/bin $path)
  export TOMCAT_HOME=$HOME/.homebrew/Cellar/tomcat6/6.0.39/libexec
  export JAVA_HOME=$(/usr/libexec/java_home)
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Terminal
#

if hash xfce4-terminal 2>/dev/null; then
  export TERMINAL='xfce4-terminal'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Homebrew setup
#

if [[ -d "/opt/homebrew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
