# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -s "$HOME/.zprofile" ]] && source "$HOME/.zprofile"

unsetopt autocd # turn off changing directory without "cd"
unsetopt nomatch # https://robots.thoughtbot.com/how-to-use-arguments-in-a-rake-task

eval "$(fasd --init auto)"

# Aliases
unalias gs
alias ssh='TERM=xterm ssh' # fix $TERM problem on remotes
alias tmux="tmux -2" # tmux with 256 colors support
alias j="fasd_cd -d"
alias vi="nvim"
alias vim="nvim"
if [ -x "$(command -v xdg-open)" ]; then
  alias open="xdg-open"
fi

# gcloud SDK command completion and PATH
if [[ -d "/usr/lib/google-cloud-sdk" ]]; then
  source "/usr/lib/google-cloud-sdk/completion.zsh.inc"
  source "/usr/lib/google-cloud-sdk/path.zsh.inc"
fi

# kubectl command completion
if [ -x "$(command -v kubectl)" ]; then
  source <(kubectl completion zsh)
fi

# kubectl context switcher + completion
function kube-context() {
  kubectl config use-context $@
}

_kube-context_completions() {
  local -a options
  options=()
  for c in $(kubectl config view -o jsonpath='{.contexts[*].name}'); do
    d=$(echo $c | awk 'BEGIN { FS="_" }; { printf "%11s: %-15s %-14s", $4, $3, $2 }')
    options=($options "$c:$d")
  done
  _describe 'Kubernetes contexts' options
}

compdef _kube-context_completions kube-context

# base16 colors
if [[ -d "$HOME/.config/base16-shell" ]]; then
  BASE16_SHELL=$HOME/.config/base16-shell/
  [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"
fi

if [[ -d "$HOME/.yarn/bin" ]]; then
  export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
fi

if [[ -d "$HOME/.rbenv/shims" ]]; then
  export PATH="$HOME/.rbenv/shims:$PATH"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.zshrc.user ] && source ~/.zshrc.user
