# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

unsetopt autocd # turn off changing directory without "cd"
unsetopt nomatch # https://robots.thoughtbot.com/how-to-use-arguments-in-a-rake-task

# Aliases
alias be="bundle exec"
alias gob="rave gob"
alias lock='/System/Library/CoreServices/"Menu Extras"/User.menu/Contents/Resources/CGSession -suspend'
alias pdo="powder open"
alias pdr="powder restart"
alias r18="spring rake i18n:js:export"
alias ssh='TERM=xterm ssh' # fix $TERM problem on remotes
alias tmux="tmux -2" # tmux with 256 colors support
alias nospring="DISABLE_SPRING=1"

alias 1pass-to-android="adb-sync ~/Documents/1Password /sdcard/"
alias 1pass-to-mac="adb-sync --reverse /sdcard/1Password ~/Documents/"
alias 1pass-sync="1pass-to-android && 1pass-to-mac"

# Experimenting with Neovim
alias vi="nvim"
alias vim="nvim"

if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.user" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.user"
fi
