# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -s "$HOME/.zprofile" ]] && source "$HOME/.zprofile"

unsetopt autocd # turn off changing directory without "cd"
unsetopt nomatch # https://robots.thoughtbot.com/how-to-use-arguments-in-a-rake-task

# Aliases
alias g="git"
alias gg="git grep"
alias ssh="TERM=xterm ssh" # fix $TERM problem on remotes
alias tmux="tmux -2" # tmux with 256 colors support
alias vi="nvim"
alias vim="nvim"
if [ -x "$(command -v xdg-open)" ]; then
  alias open="xdg-open"
fi

# gcloud SDK command completion and PATH
if [[ -d "/usr/lib/google-cloud-sdk" ]]; then
  source "/usr/lib/google-cloud-sdk/completion.zsh.inc"
  source "/usr/lib/google-cloud-sdk/path.zsh.inc"
fi

# kubectl command completion
if [ -x "$(command -v kubectl)" ]; then
  if [ ! -f "$HOME/.kubectl.zsh" ]; then
    kubectl completion zsh > "$HOME/.kubectl.zsh"
  fi
  source "$HOME/.kubectl.zsh"
fi

if [[ -d "$HOME/.yarn/bin" ]]; then
  export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
fi

# https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
NPM_PACKAGES="${HOME}/.npm-packages"
if [[ -d "$NPM_PACKAGES" ]]; then
  export PATH="$NPM_PACKAGES/bin:$PATH"
fi

if [[ -d "$HOME/.rbenv/shims" ]]; then
  export PATH="$HOME/.rbenv/shims:$PATH"
fi

[ -f ~/.zshrc.user ] && source ~/.zshrc.user
